reHackable/awesome-reMarkable

- README.md
Makes more sense to link ~jGrass~ reMarkable-hyutilities source code / github page.
Would love to know what @moovida thinks about the change.
> Change jGrass link to github page

- README.md
Add en entry about a way to print to reMarkable Cloud from CUPS, links to code in the article.
> Add CUPS printing entry

- README.md
I created a script to send an arXiv paper to the reMarkable with a single command. The script downloads the paper, crops the pdf, and sends it to the reMarkable using rMapi. Thought it might be useful to add to this list.
> Add arxiv2remarkable to device tools

- README.md
Add rmuploader - A simple web tool that can be launched with Docker and that provides drag and drop to upload a PDF or EPUB onto the tablet (via the Cloud).
> Add rmuploader

- README.md
I deprecated it in favor of reMarkable-typescript
> Removed reMarkable-node

- README.md
A while ago I added the arxiv2remarkable script I wrote to this list. That script has since grown into a Python package for sending documents quickly to the remarkable, including academic papers from various sources as well as HTML articles. This description hopefully better captures what the package does.
> Update description of paper2remarkable

- README.md
previously it had to be run on your pc and synced with the remarkable program. now it runs on the reMarkable directly. text is updated to reflect this and moved to other category
> pocket2rm can now be run on remarkable

- README.md
Add link to [Crazy Cow](https://github.com/machinelevel/sp425-crazy-cow/blob/master/README.md), which provides typewriter input from USB keyboard directly into reMarkable interface.
> [add line] Add crazy cow link and description

- README.md
Add a listing for [an automatic PDF creator from RSS/news feeds](https://github.com/j6k4m8/goosepaper).
> Add goosepaper tool

- README.md
Just noticed, that toltec already packages [sandmark](https://github.com/sandsmark/)'s [recrossable](https://github.com/sandsmark/recrossable) but is not in this list, yet.
The description is taken from the description of the respective repo.
> Add sandmark's recrossable

- README.md
goMarkableStream is a simple client-server to stream the content on the remarkable in a secure way without needing any third-party software (such as ffmpeg)
> add goMarkableStream

- README.md
I started working on an ebook downloader for reMarkable. 
It's still in the early stages, but usable. It uses rmkit,okp for ui and golang for the backend. Currently only standardebooks.org site is supported.
> The missing book store for remarkable.

- README.md
I developed this small script in order to keep my PDF files from multiple WebDAV sources up-to-date on my reMarkable.
> Add remarkdav as API tool

- README.md
Mostly this serves to separate the reMarkable Cloud API libraries from the
libraries for reading the Lines format.
> Add subcategories for the "APIs" section

- README.md
Add the following project to the Lines Format section:
- [reMarkable-kaitai](https://github.com/matomatical/reMarkable-kaitai) - [Kaitai Struct](https://kaitai.io/) format specification for the binary lines format.
Extended description:
- [reMarkable-kaitai](https://github.com/matomatical/reMarkable-kaitai) - A [Kaitai Struct](https://kaitai.io/) format specification for the binary lines format. Can be used to generate parser code in various languages. Based on the same reverse engineering results as lines-are-beautiful/lines-are-rusty.
> Add reMarkable-kaitai

- README.md
Add [rm-pdf-tools](https://github.com/skius/rm-pdf-tools) to the "Cloud Tools" section. It adds rudimentary (for now) PDF-editing capabilities to the reMarkable tablet using the reMarkable Cloud.
> Add rm-pdf-tools

- README.md
Add [remarking](https://github.com/sabidib/remarking), a tool for extracting highlights from your reMarkable documents in the cloud.
> Add remarking to the list of cloud tools

- README.md
Adds [reCalendar](https://github.com/klimeryk/recalendar), a highly customizable calendar optimized for reMarkable.
See also [the discussion on reddit](https://www.reddit.com/r/RemarkableTablet/comments/odpl07/recalendar_opensource_highly_customizable/). I got some great feedback and I feel the project is worthy of inclusion on this list 🙇
> Add reCalendar calendar

- README.md
This adds resync.py and related scripts to the list of tools for the remarkable.
> Add remarkable-tooling to the list of available tools

- README.md
Hi! This is sort of related to my previous PR: https://github.com/reHackable/awesome-reMarkable/pull/145
But https://recalendar.me/ (source code here: https://github.com/klimeryk/recalendar.js/) is a complete rewrite of that project. This time as a modern, easy to use webapp. No need to install anything, everything is done in browser (including PDF generation). Plus, lots of other [features](https://recalendar.me/features). Hope you like it!
PS: I've adjusted the captialization to `ReCalendar`, as originally I got confused by the contributing guidelines. I thought the `reMarkable` rule applied to everything, but I now see there's a clear distinction that it does _not_ apply to project/repos. Since I've been using `ReCalendar` everywhere and not `reCalendar`, I wanted to go with that. …
> Add recalendar.me online calendar generator

- README.md
I know it's already in the Toltec setup instructions, but I think another warning here would be good for people that tend to rush through things. Thanks!
> Add another warning about the SSH password

- README.md
[reGenda](https://github.com/tenJirka/reGenda) is read only agenda app for reMarkable. 
It shows your events from calendar via caldav.
> Add reGenda

- README.md
[rm-pySAS](https://github.com/tenJirka/rm-pySAS) is python wrapper around [simple](https://rmkit.dev/apps/sas).
It can be used to create simple applications for reMarkable in Python.
> Add rm-pySAS

- .github/workflows/ci.yml
- README.md
The link to my Figma templates was removed in #201—ReMarkable did a trademark takedown on them :-(
I've re-published them named as "Templates for ReMarkable" instead of "ReMarkable Templates" so hopefully they'll leave it alone this time...
> Restore link to Figma templates

- README.md
Hi
Thanks for the awesome repo. I added a link to a tool I made called `kindle2pdf` which I use to be able to read Kindle books on my reMarkable. I hope you consider including it. Thanks!
> Added kinde2pdf

- README.md
As of July 2nd of 2024, rMAPI has been archived on GitHub. Because of this and this [note by the maintainer](https://github.com/juruen/rmapi/discussions/313) the project is now unmaintained.
> feat: mark rMAPI as unmaintained

- README.md
Added links for browser extensions that create ePubs and can either upload them to reMarkable cloud or save them locally
> Add a section on browser extensions

- README.md
As of now, the default Web UI for local export doesn't support downloading folders and fails on large notes. To fix this I wrote my own tool 'rm-exporter'.
> Add rm-exporter

- README.md
**reLuminate** unlocks enhanced brightness levels for the reMarkable Paper Pro, giving you more control over your screen’s reading light. Say goodbye to the factory’s lackluster brightness settings!
- **Enhanced Brightness Levels** – Adjust the screen lighting beyond the default limitations.
- **Persists Across Reboots** – Access to enhanced brightness settings stay in place even after restarting your device.
- **Simple Installation** – A simple install script takes care of the setup, so you don't have to.
> Add reLuminate

- README.md
It seems the current state of remarkable cloud API tools is pretty bad. most seem to be unmaintained/inactive. I update the readme to reflect this.
> Mark some cloud API projects as unmaintained

- README.md
[lucaslra's remarks repository](https://github.com/lucasrla/remarks) hasn't received an update in two years, and doesn't support the RMPP or recent versions of the reMarkable software.
I've updated it to [my fork of remarks](https://github.com/Scrybbling-together/remarks), which is actively maintained, and does support the RMPP and recent versions of the reMarkable software.
> Update remarks repo to fork that is still active
