README.md
I am requesting to add my web-application implementation of the reMarkable cloud API using the ES6 ReactJS framework and a backend built on Google's Firebase Servers.
I have currently added rudimentary document rendering support using HTML5 canvas and fetch calls/unpacking apis for downloading remote files from the remarkable servers. I plan to add editing features to the web app so that users can edit their notebooks from their computers or phones. I also plan to add support for document PDF exporting as well as PDF uploading within the next couple of months.
Thank you for considering my pull request!
=> Added web interface application from rioam2

README.md
Hello,
I would like to add my project to your list.
Regards,
Simon Baudart
=> Add the project "Funcky.Remarkable.Exporter"

README.md
This is a small script that I wrote that syncs PDFs from a folder in Zotero to my reMarkable device. Since I read a lot of papers I've found this very handy and hopefully others do too :)
=> Add zotero-remarkable

README.md
A GUI written in Python/Qt5 to explore files on the tablet and download them as PDF or PNG. Allows downloading whole folders at once.
=> Adding rMExplorer

README.md
Instructions and systemd unit for setting up [Syncthing](http://wikipedia.org/wiki/syncthing).
=> add syncthing

README.md
[remarkable_mouse](http://github.com/evidlo/remarkable_mouse) and [remarkable_pdflets](http://github.com/evidlo/remarkable_pdflets).
=> add remarkable_mouse, remarkable_pdflets

README.md
made a simple app to enable/disable touch navigation
=> Add remarkable-touchgestures

README.md
Add jrmapi to the APIs section
=> Add jrmapi to the APIs section

README.md
Add reMarkable-wikipedia - an offline wikipedia reader.
=> Add reMarkable-wikipedia

README.md
rMExplorer has grown a lot!  It now uses SSH for some tasks in addition to
USB.
=> Updating rMExplorer description

README.md
More info on the app can be found at https://blog.singleton.io/posts/distraction-free-writing/
=> Add remarkable keywriter - a distraction free keyboard notes app

README.md
Add the Rust companion library for the `.rm` file format.
=> Add Rust File API

README.md
Added a cloud API to the README
=> Add remarkable-typescript

README.md
Change your poweroff and suspend screens every 5 minutes with random images of your choice
=> Change screens every 5 minutes with random images

README.md
1. Added ReMy
2. Changed description of rMview to reflect new VNC branch
=> ReMy tool and description of rMview

README.md
(see https://old.reddit.com/r/RemarkableTablet/comments/hooadx/rmharmony_a_sketching_app_for_remarkable_tablet/ for more info, potentially)
=> add harmony sketching app

README.md
Hi,
a few weeks ago I made this. I may continue making smaller games simply to learn rust. There is also an older game [recrossable](https://github.com/sandsmark/recrossable) which never made it here. I have not tested that, but is also probably worth adding.
=> Add retris

README.md
update harmony to use rmkit.dev link
=> apps: add remux launcher to launcher section, add minesweeper

README.md
Improve categorization.
Credits to [Davis](http://www.davisr.me/) for the GUI Clients ideas.
No elements added/removed
=> Reorganize list, add RCU and Parabola-rM

README.md
=> Added Android App - RemaDroid

README.md
Options were discussed here: https://github.com/reHackable/awesome-reMarkable/issues/70
Since, there was no responde from darvin, i choose the option, I found best a few months ago in that issue (good combination of short and yet informative without needing to click any links imo).
=> Add 2nd plato

README.md
Add [reSnap](https://github.com/cloudsftp/reSnap), a tool to take screenshots via ssh.
Also remove trailing white spaces.
=> add reSnap

README.md
Hello, I wrote a postfix filter to upload PDF documents to the cloud by email. It could be of help to others.
=> Add mail2rm

README.md
Add link to utility useful for converting pdf documents for easier reading in landscape mode.
=> Add link to landscape-pdf

README.md
Reddit launch: https://www.reddit.com/r/RemarkableTablet/comments/iwelzo/releasing_my_shared_whiteboard_app/ (I had lots of fun there. Especially when people started chatting. I was not expecting this at all!)
Find the app within https://github.com/fenollp/reMarkable-tools
It is all open source and self-host-able. I am running an instance that clients connect to by default. Not logging anything.
*This is only the beginning*
=> Add my whiteboard-hypercard rM app

README.md
=> Add Julia API repo

README.md
Add reMousable to others.
Closes #89
=> Add reMousable

README.md
This seems to be where the other libraries that can read annotations are, so I hope it's the right place.  Let me know if there's a better category for it.
=> Add rmrl to APIs

README.md
Looking for a good way to warn about the non-obvious risks when modifying the device, like:
- Factory reset not fixing some issues and resetting ssh password
- rM2 recovery requiring hardware
- reMarkable TOS and warranty (is this really important?)
I'm not a native speaker so reviews are welcome.
=> Improve disclaimer

README.md
This is a project I have recently started to sync between Simplenote and my reMarkable. The tool is built out enough to be useful but still has a way to go before I am done with it.
=> Add remarkable_simplenote

README.md
=> add Drawj2d

README.md
Disclaimer: I am the creator of [rm.ezb.io](https://rm.ezb.io/), not sure if that is allowed here.
This is a website meant to make it easier to search for and peruse reMarkable templates.
=> Add rm.ezb.io to Custom Templates

README.md
- [reMarkable Template Builder](https://templarian.github.io/remarkable/) - Generate Isometric and Grid templates of all sizes
- [Remarkable Grid Template Generator](https://xosh.org/remarkable-grid-template/) - Generate pixel perfect line grid and dotted grid templates (i made this one)
- [NoTeTo](https://noteto.needleinthehay.de/) - Design templates by drag and drop components
=> Add three template generators

README.md
Add Calibre-Remarkable-Device-Driver-Plugin, a calibre plugin to manage your remarkable books
=> Add Calibre-Remarkable-Device-Driver-Plugin

README.md
Added a link to my repo: https://github.com/anilkyelam/mendeley-rMsync
=> Added a suggestion with a sync tool for Mendeley

README.md
Adds doomarkable to the games section
=> Add doomarkable

README.md
Hey! I've made this app to receive PDFs and epubs from Telegram directly to your reMarkable 2 without the need of an additional server, I hope it will be useful for other people. :)
=> [remarkaBot](https://github.com/Davide95/remarkaBot) - Fetch your documents from Telegram

README.md
From the project `pipes-and-paper`, not updated since 2020, I forked it to enhance it (colors pen, eraser support, etc.)
=> Add Pipes and paper enhanced

README.md
I thought device tools was the most appropriate category as you install the program on the device. Please feel free to move it somewhere more appropriate.
Information and instructions in README. Thanks!
=> WebInterface-Wifi

README.md
Adds the reMarkable crosswords project, a user script that delivers crops and delivers crosswords to a reMarkable
=> Add reMarkable crosswords

README.md
Add remarkable Lamy Eraser project for Lamy Al star stylus pen
=> Add RemarkableLamyEraser

README.md
Neofetch fork for the ReMarkable, with minimal tweaks.
tested on rM1 and rM2
Thanks!
=> Add Other: neofetch

README.md
Hi!
I normally wouldn't bother plugging myself in, but I don't see anything equivalent (ddvk's remarkable-touchgestures is close but not quite as flexible) and this might interest other hackers...
I didn't add my pipes-and-paper fork I did a few years back and someone else did another fork to also handle eraser recently, so might as well consolidate, and it's easy to hack & good enough to use.
Cheers & thanks for this repo!
=> Add remarkable-shortcuts

README.md
https://github.com/reHackable/awesome-reMarkable/issues/128
=> Tutorial for adding a microSD card

README.md
rmWebUI - Simple web interface for the cloud
- [source](https://github.com/polletfa/rmWebUI)
- [live demonstration](http://frmpollet.me/rmWebUI-demo)
=> rmWebUI - Simple web interface

README.md
This adds my tool book-safe. Its a binary that runs on the remarkable and hides/locks documents away within a preset time period. I honestly use it to go to bed on time. 
I have been using it for over a year now and I feel its stable and ready for wider use.
=> Add book-safe app/tool to other

README.md
Request to add my python-based script, that allows syncing files from Zotero to reMarkable and back.
=> Add Zotero2reMarkable Bridge

README.md
The project may be not on the intuitive side of things but it hits the flexibility quite a bit.
=> Add blank_slate_pdf

README.md
- Indicate which repos have been archived.
- Fix order of entries in categories.
- Move items to appropriate categories.
- Switch oxide link to main website.
=> Clean up list

.github/workflows/ci.yml, README.md
Solves https://github.com/reHackable/awesome-reMarkable/issues/190
=> feat: Add awesome_bot as a GitHub Action

README.md
Can you add my application "reMarkable Remember" to list, please?
=> Add: reMarkable Remember

README.md
Hello, can you add my re-Planner to list?
Thank you.
=> Add re-Planner

README.md
Adding a project I created which allows syncing substack articles to the reMarkable.
=> Add remarkable-substack

README.md
A physical foot pedal to turn pages on the reMarkable without using hands.
=> Add paginator

README.md
This commit updates the entry for reMarkable Connection Utility (RCU) with a minimal, up-to-date features list.
=> Update entry for RCU

README.md
Updated Readme with a new tool called Remarkable RSS to read RSS feeds on remarkable device.
=> Add Remarkable RSS

README.md
This is a script I just made to install entware / opkg on RMPP, inspired by rmpp_entware.
=> Add RMPP Entware

README.md
Hi, I renamed a repository and updated the link here accordingly
=> Rename kindle2pdf to pdf2remarkable

README.md
* adding EPUB to reMarkable PDF web service
* simple web interface to create a reMarkable optimised PDF out of an EPUB
=> Add epub_to_remarkable

README.md
Request to add my recent project to the list.
Ephemeris - A Python-based tool that generates clean, daily schedules using ICS calendar data. Designed with e-ink tablets like reMarkable in mind.
=> Add Ephemeris

README.md
Adds my project rss2remarkable to the list 
https://codeberg.org/akselmo/rss2remarkable
=> Adds rss2remarkable

README.md
An AI agent for processing RSS news feeds and sending them to reMarkable via Google Drive API
=> Add AgentNews-RemarkableRSSReader

README.md
added rmtree and corrected the alphabetization in this section.
=> add rmtree
